# Generated by Django 3.1.3 on 2020-11-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='requested_price',
            new_name='average_price',
        ),
    ]
