# Generated by Django 3.1.3 on 2020-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201115_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no_iva',
            field=models.IntegerField(default=0),
        ),
    ]
